### ISSUE TITLE
Missing Options in Spectrum Theme's color & font preferences

### ISSUE THREAD

**Issue by KhalebOBrien** [AObuchow/Eclipse-Spectrum-Theme#135]
According to the .readme file, 

"Open Eclipse's preferences and navigate to General >> Appearance >> Colors and Fonts. The plugin's color & font preferences are under the Spectrum category folder."

The only option available there is "Project Explorer". Please, where do I find these options?
I would suggest that the plugin should be loaded after installation as expected.

![issues](https://user-images.githubusercontent.com/28302748/93095610-3b17ca00-f69b-11ea-85e4-c2c766c9bb8f.png)

Here's my version of Eclipse:
Eclipse IDE for Enterprise Java Developers (includes Incubating components)
Version: 2020-06 (4.16.0)
Build id: 20200615-1200

Am running Windows 10, 64x

**Comment by AObuchow** [comment]
> According to the .readme file,
> 
> "Open Eclipse's preferences and navigate to General >> Appearance >> Colors and Fonts. The plugin's color & font preferences are under the Spectrum category folder."
> 
> The only option available there is "Project Explorer". Please, where do I find these options?

Hm this is very strange, I've tested the plugin on Windows and the color preferences were available. Perhaps it's because I was using the Eclipse SDK and not Eclipse IDE for Enterprise Java Developers (includes Incubating components). I'll try to reproduce this when I have a moment.

In the meantime: are there any other color preferences that are available to you? Or is it only Spectrum theme's color preferences that are missing?
Ie. Under "basic" do you see "description color"?
![image](https://user-images.githubusercontent.com/10300119/93116295-14ea2e00-f68b-11ea-83e7-1cb5d94c203a.png)

Also IIRC, @PyvesB [Planet Themes](https://github.com/PyvesB/eclipse-planet-themes) have customizable color preferences as well. Are those available to you? (@PyvesB correct me if I'm wrong!)


> I would suggest that the plugin should be loaded after installation as expected.
> 

Do you mean like https://github.com/AObuchow/Eclipse-Spectrum-Theme/issues/93?


> Here's my version of Eclipse:
> Eclipse IDE for Enterprise Java Developers (includes Incubating components)
> Version: 2020-06 (4.16.0)
> Build id: 20200615-1200
> 
> Am running Windows 10, 64x

Thanks for the info and sorry for the issue with the plugin, I'm quite perplexed as to why you're encountering this issue. Hopefully we'll find out why soon and get that fixed for you :)

**Comment by PyvesB** [comment]
> Also IIRC, @PyvesB [Planet Themes](https://github.com/PyvesB/eclipse-planet-themes) have customizable color preferences as well. Are those available to you? (@PyvesB correct me if I'm wrong!)

You are indeed correct!

**Comment by AObuchow** [comment]
@KhalebOBrien it just occurred to me: if you don’t have spectrum theme set as your active eclipse theme, I don’t think spectrum themes colour preferences are visible.

Can you try setting your eclipse theme to Spectrum Theme then check the colours & fonts preference page for spectrum themes colour settings?

**Comment by KhalebOBrien** [comment]
> @KhalebOBrien it just occurred to me: if you don’t have spectrum theme set as your active eclipse theme, I don’t think spectrum themes colour preferences are visible.
> 
> Can you try setting your eclipse theme to Spectrum Theme then check the colours & fonts preference page for spectrum themes colour settings?

@AObuchow you are right! I had to set Spectrum Theme to my active eclipse theme before it started working. Everything is alright now. Thanks to your quick response.

> Do you mean like #93?

Yes @AObuchow that's exactly what I meant. Am glad it's on the ToDo list.

@PyvesB I even had to install Planet Themes but it did not appear in my list of installed themes. Anywhere, Spectrum Theme is actively working for me. Thanks for your help.
