### ISSUE TITLE
Content Assist selection not visible on Windows

### ISSUE THREAD

**Issue by DKLEEE** [AObuchow/Eclipse-Spectrum-Theme#72]
Hi,
in the Content Assist Hover it is hard to so which line is selected.

In this Example the the 4. entry is selected.

![grafik](https://user-images.githubusercontent.com/16030367/85276654-79c62b80-b482-11ea-87dc-ae1ea6ed6815.png)

Plugin Version: 1.0.7.202006190441
Eclipse: 2020-06
OS: Windows

**Comment by PyvesB** [comment]
Hello @DKLEEE, I think this is upstream bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=562043 😉

**Comment by DKLEEE** [comment]
Thanks for info. 
So it seems it is not a Problem of this Plugin, feel free to close it here ;)

**Comment by AObuchow** [comment]
@DKLEEE one way we can confirm it’s an upstream issue is to see if the same issue exists when using Eclipses default Dark theme. If you have a moment and can test this out, it’d be greatly appreciated :)

**Comment by DKLEEE** [comment]
Can confirm, the Eclipse Default Dark Theme has the same Problem ;)

**Comment by AObuchow** [comment]
@DKLEEE pleased to let you know this is now fixed in Eclipse upstream. The fix will be available in Eclipse 4.17 coming in september: https://bugs.eclipse.org/bugs/show_bug.cgi?id=562043 :) The fix also allows context-menu's (right-click menus) to be dark on Windows, which is really awesome :D 

I'm going to close this issue now that the upstream bug is resolved.
